```{mermaid}
flowchart LR
  VanderWeele2009a[VanderWeele 2009] --> VansteelandtVanderWeeleTchetgen:2008[Vansteelandt et al. 2008]
```

# Interaction and Effect Modification

From the abstract of [@VanderWeele:2009a]:

> This paper contrasts the **concepts of interaction and effect modification** using a series of examples. Interaction and effect modification are formally defined within the **counterfactual framework**. Interaction is defined in terms of the effects of 2 interventions whereas effect modification is defined in terms of the effect of one intervention varying across strata of a second variable. Effect modification can be present with no interaction; interaction can be present with no effect modification. There are settings in which it is possible to assess effect modification but not interaction, or to assess interaction but not effect modification. The **analytic procedures** for obtaining estimates of effect modification parameters and interaction parameters using **marginal structural models** are compared and contrasted. A characterization is given of the settings in which interaction and effect modification coincide.

From the abstract of [@VansteelandtVanderWeeleTchetgen:2008]:

>
